### ISSUE TITLE
Improve the examples in the README and document best practices

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-top-level-await#116]
The examples that we have in the README are not very realistic, and don't really represent best practices for using top-level await. As this proposal is at Stage 3 and will be getting more and more visibility, it's time to make sure we have strong examples of when it makes sense to use this feature, through the motivation and use case sections. I think we should also have admonitions to not use this feature when it would slow down startup time, and more practical examples of how the "Variant B" semantics are good in practice for putting unrelated pieces of initialization code in parallel.

cc @bkardell

**Comment by codehag** [comment]
Closing as we are at stage 4. A better place might be MDN?
