### ISSUE TITLE
Tracking: Platform integration

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-top-level-await#119]
* [x] HTML
  * #45 
  * https://github.com/whatwg/html/pull/4352
* [x] ServiceWorker
  * #79 
  * https://github.com/w3c/ServiceWorker/issues/1407
  * https://github.com/w3c/ServiceWorker/pull/1444
* [x] `import()`
  * #46 
  * https://github.com/tc39/proposal-dynamic-import/pull/71

**Comment by codehag** [comment]
(dynamic import changes are now part of this repo)
