### ISSUE TITLE
for await

### ISSUE THREAD

**Issue by syg** [tc39/proposal-top-level-await#132]
Confirming that it is intended that `for await` is also available at module top level, in addition to *AwaitExpression*.

I see no reason that this should not be the case, so it seems the case that step 12 of [ParseModule](https://tc39.es/proposal-top-level-await/#sec-parsemodule) needs to be patched to be aware of `for await`.

**Comment by RangerMauve** [comment]
Oh my, having this would make a lot of node scripts so much easier. Making small utilities for dealing with file streams won't require wrapping everything in a `run` async function or the such.
