### ISSUE TITLE
What about `import <name> from async '<module>'`?

### ISSUE THREAD

**Issue by ExE-Boss** [tc39/proposal-top-level-await#134]
I stumbled upon this gist from @Rich-Harris:

https://gist.github.com/Rich-Harris/1c44b7caed5c4ac2aadb2e2cd1028fdc

**Comment by MylesBorins** [comment]
Hey @ExE-Boss this was discussed quite a bit and resulted in changes to the spec to allow disconnected graphs to continue to execute

Please take a look at Rich's edit to his original footgun article to see his current feelings on the proposal

--> https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221

This is somewhat similar to the `import await` proposal that came later... for a more in depth response please take a look at this gist

--> https://gist.github.com/MylesBorins/ae97abab4a4144411c12240bb09dc7dd

The notes from when Top-Level Await went stage-3 has some details you might enjoy reading as well

--> https://github.com/tc39/tc39-notes/blob/master/meetings/2019-06/june-6.md#top-level-await-for-stage-3

I'm going to close this issue for now, but happy to answer more questions. FWIW generally when a proposal reaches stage-3 we don't make large changes aside from bug fixes unless implementations find something fairly significant. In the case of Top-Level Await it has already been implemented in V8 (behind a flag)
