### ISSUE TITLE
behavior on the conditional imports

### ISSUE THREAD

**Issue by serkanyersen** [tc39/proposal-top-level-await#142]
Hi All,

Sorry if this is a naive question, I'm trying to figure out the behavior of top-level dynamic imports in conditional situations.

Some examples

```javascript
const { env } = await import('./env');
const { foo } = await import(`./foo-${env}`);
```

or 

```javascript
import { checkFooEnabled } from '../checks';
let Foo = false;
if (checkFooEnabled()) {
  Foo = await import('./foo')
}
const Bar = await import('./bar');
```

I'm assuming these are all blocking operations and will have to wait for each other to move forward. Is this a correct assumption? Proposal does not address this directly and I thought I would ask.

Thanks!

**Comment by MylesBorins** [comment]
a top-level await will block execution in the module where it appears as well as it's parent. Sibling modules will be able to execute. The semantics of this are covered in [this section](https://github.com/tc39/proposal-top-level-await#semantics-as-desugaring) of the explainer.

I'm going to close this PR but please feel free to ask any other questions you might have.
