### ISSUE TITLE
Host behavior enforced by tests, but not mentioned in the spec

### ISSUE THREAD

**Issue by codehag** [tc39/proposal-top-level-await#150]
While working on Top Level await in Firefox, I came across a few failures that were not referenced in the specification, but were outlined in the HTML specification. Namely, this test: https://searchfox.org/mozilla-central/source/js/src/tests/test262/language/module-code/top-level-await/module-import-rejection.js#75

It expects an unwrapped error, while the specification suggests that we will have a rejected promise. As mentioned, this is clarified in the html specification: https://whatpr.org/html/4352/29b75ea...ea79a7f/webappapis.html#calling-scripts (in the segment "to run a module...". It was suggested in the spidermonkey chat that we add some prose making it explicit that this is done by the host with respect to unwrapping the promise.

**Comment by Ms2ger** [comment]
I think I understand your concern, and perhaps a note in [Table 2: Abstract Methods of Module Records](https://tc39.es/proposal-top-level-await/#table-37) would help, but I'm not quite sure how to phrase it. Do you have thoughts?
