### ISSUE TITLE
[Spec] update parts of the spec for Module Record's Evaluate() returning a promise

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-top-level-await#17]
There are a few places in the spec that talk about Module Record's Evaluate() returning or throwing. They need to be updated to talk about returning a fulfilled/rejected promise.

- https://tc39.github.io/ecma262/#table-37
- https://tc39.github.io/ecma262/#sec-example-source-text-module-record-graphs
- https://tc39.github.io/ecma262/#sec-toplevelmoduleevaluationjob, but see https://github.com/tc39/ecma262/pull/735; this may not be worth worrying about
- ... more?

**Comment by littledan** [comment]
This has been fixed.
