### ISSUE TITLE
[Spec] Also spec variant B

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-top-level-await#19]
First we're going to land variant A because it's easy to spec. Then we'll work on a spec-level Promise.all and spec variant B alongside.

**Comment by littledan** [comment]
@guybedford did a great job of spec'ing variant B in #33.

**Comment by zenparsing** [comment]
I'm currently in favor of variant A, since it is easier for users to reason about the order of execution. What are the arguments in favor of variant B?

**Comment by littledan** [comment]
The big advantage of B is that it allows more parallelism, potentially reducing module load time. I think B is intuitive, as many developers understand await means "go and do something else" and not "stop the whole world while I look for the answer". Many people would prefer that the system parallelize things when possible (for performance), e.g., see Rich Harris's gist which was largely about these performance concerns.

Can you explain the concern about reasoning about execution order a bit more? There's been a bit of confusion in the past about how B works; it seemed like many practical concerns (e.g., for polyfills) were about modules *starting* in the right order, which B preserves.

**Comment by zenparsing** [comment]
> Can you explain the concern about reasoning about execution order a bit more?

With the current design, a "root module" can order side-effects of its dependencies:

```js
import 'a';
import 'b';
```

With variant B, we lose some of this property if an `await` is inserted into the body of module "a". All other things being equal, it seems like the root module should be able to depend on this ordering property without having to know if "a" contains an `await` or not.

Also, from a beginner's intuitition point of view, it seems more intuitive to think of the import as "awaiting" the module before doing "the next thing".

I don't think we should give up on these aspects of the current design without a substantial offsetting benefit. Is there a motivating use case which demonstrates the parallelism benefit?

**Comment by littledan** [comment]
Yes, I agree that we should do more to research and document practical use cases for this parallelism. Three that I have in mind:
- Dynamically loading JavaScript code when the need is determined during startup, to make it available for all users of the module. As this involves network access, and multiple module subgraphs may need to pull down unrelated code and not have any need for coordination, it could reduce load time to have this be in parallel. It may be a little subtle when this makes sense, and I see examples floating around that aren't convincing to me, but here's a couple cases where I can see it coming up, which would each benefit from parallelism:
  - Load different JavaScript files based on locale or user preference
  - Load a replacement for a built-in module *only if* that built-in module is not present locally. See https://github.com/WICG/import-maps#alternating-logic-based-on-the-presence-of-a-built-in-module for more details about this case.
- Grabbing unrelated external resources. Maybe a module wants to get in touch with a database over the network, or locally, on startup and export functions that you can use to talk to it. Top-level await becomes impractical for this sort of use case if it blocks unrelated other asynchronous work from happening in parallel. However, I'm not sure how important this case is.
- WebAssembly module instantiation would benefit from greater parallelism, as I sketched in https://github.com/tc39/proposal-top-level-await/issues/35#issuecomment-462160359 . This doesn't need top-level await to be exposed to JavaScript, but it does require that we figure out how dependencies will be orchestrated; it doesn't seem practical to have looser guarantees just for WebAssembly.

When there is a relationship between two modules, the pattern would be that one would import the other. Polyfills today don't use top-level await, and will continue to deterministically execute before when they don't. I don't think we should encourage new code to be written in a "block the world until an asynchronous action happens" pattern, as Variant A would enable lots of code do (very easily, and maybe without even making it clear to the programmer that they are having this effect).

It'd be great to reach out to a larger population of JavaScript programmers to understand how these use cases relate to their programming needs.

**Comment by littledan** [comment]
The explainer is updated with more use cases, and the spec text uses Variant B, so closing this issue.
