### ISSUE TITLE
More information wanted about TDZ vs partial initialization

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-top-level-await#22]
A pretty tricky part of this proposal is the end, about handling cycles. The idea of rejecting the Promise in the cyclic case seems attractive because it is more minimalistic and means that a resolved import signifies that the initialization code has completed.

You mention that a downside is that it doesn't support certain cases that CJS supports. Could you be a little more concrete about what sorts of scenarios this comes up in? I really like the use cases you have elsewhere in the README.

I don't see specification text which describes either solution. Was this omission deliberate?

**Comment by domenic** [comment]
My understanding is that the current specification text takes a minimal approach and does not try to detect cycles, and so will use the normal behavior for cyclic modules (plus of course waiting on any awaits). Is there a problem with the spec text in this regard, or is this issue just saying that you'd like to add additional cycle detection spec text?

**Comment by littledan** [comment]
@domenic This isn't about what I am saying I want--the ideas about handling cycles are all from the explainer.

**Comment by domenic** [comment]
I see. We should probably remove that and just defer to the spec text.

**Comment by MylesBorins** [comment]
So should we remove the tdz / cycle stuff from proposal?

**Comment by littledan** [comment]
IMO we should raise these three possibilities to a larger audience. I bet there will be others who are uncomfortable just accepting a deadlock where CJS completes successfully in an analogous case.

**Comment by littledan** [comment]
@GeorgNeis wrote a document examining various possibilities for how to handle the cycle case. In the end, it seems like there's no good, general solution to dynamic deadlock detection without seriously breaking other, more common and useful cases. Note that a cycle of static imports does not cause deadlocks. This conclusion was presented at the March 2019 TC39 meeting without further concerns raised, so closing the issue.
