### ISSUE TITLE
Optional Constraint 2: can only use in "entry points"

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-top-level-await#26]
https://github.com/MylesBorins/proposal-top-level-await#optional-constraint-top-level-await-can-only-be-used-in-modules-without-exports

Another alternative to "only in modules without exports" is "only entry points" - in a browser, this would be "script tags" or "files used to run a Worker" ; in node, the thing used to start an app; and in both, anything that's `import()`-ed.

There are some drawbacks to this, including that you could write a file that could only be dynamically and not statically imported, but I think it's worth calling out the alternative (even if that's to explain "why not").

**Comment by domenic** [comment]
This doesn't work because a file can be used as both an entry point and a dependency.

**Comment by ljharb** [comment]
@domenic sure; but when used as one, it could parse, and as the other, be an early error, no?

**Comment by domenic** [comment]
At least on the web we do not re-parse/instantiate/evaluate the same URL multiple times; doing so would interfere with the module map mechanism.

**Comment by littledan** [comment]
I don't really see what the problem would be in plumbing "no entry points" through to HTML. It'd be more bookkeeping, sure, but it all seems doable. But anyway, the explainer documents the motivation for why we are not proposing this restriction, so I'm closing this issue.
