### ISSUE TITLE
Use of Await in Evaluate() Concrete Method is invalid

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/proposal-top-level-await#32]
Await assumes that there are at least two execution contexts on the stack, which is not given here.

**Comment by guybedford** [comment]
I believe the core issue here is being tracked in https://github.com/tc39/proposal-top-level-await/issues/18.

**Comment by littledan** [comment]
Potential solution in https://github.com/guybedford/proposal-top-level-await/pull/1 , which just avoids using Await.

**Comment by littledan** [comment]
#33 has landed, fixing the issue.
