### ISSUE TITLE
Let's have a call to discuss the proposal

### ISSUE THREAD

**Issue by MylesBorins** [tc39/proposal-top-level-await#42]
/cc @ljharb @zenparsing @littledan @domenic

**Comment by littledan** [comment]
Cc @GeorgNeis

**Comment by sindresorhus** [comment]
Did this happen? If yes, can anyone comment on the progress? 🙏

**Comment by MylesBorins** [comment]
We need to get a call going! I'll get a doodle together when I'm back at
keyboard for the week of the 18th of feb

**Comment by MylesBorins** [comment]
https://doodle.com/poll/hxcsbxs9nb4usvsh

**Comment by MylesBorins** [comment]
Picking Monday at 2pm EDT

LMK if you want a cal event

Join --> https://meet.google.com/eud-pgwt-agd for the call

**Comment by MylesBorins** [comment]
just changed time to 3pm ET to help @ljharb attend. Sending a cal event out to people who's email addresses I have

**Comment by littledan** [comment]
This call happened. Thanks everyone for the great discussion!
