### ISSUE TITLE
Tracking: ServiceWorker interaction

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-top-level-await#79]
It's not clear how/whether top-level await plays well with ServiceWorkers. See https://github.com/w3c/ServiceWorker/issues/1407 for discussion.

**Comment by annevk** [comment]
I think we should offer an internal slot on agents to disable this that we can set on service worker agents.

Service worker scripts run with different states and when processing events such as fetch there really shouldn't be anything blocking the execution of its listener callbacks.

**Comment by jakearchibald** [comment]
```js
// 1
import './this-has-top-level-await';

// 2
const modulePromise = import('./this-has-top-level-await');

// 3
await modulePromise;
```

In a service worker, 1 and 3 are bad because they delay important events. However, 2 is fine.

Do we want to allow 2? It provides a path to including third party libraries that use top-level-await.

**Comment by domenic** [comment]
I would like to advocate for "let the user do the bad thing if they want". Remember, top-level await is largely sugar over what would be accomplishable today. (Powerful sugar, because of how it allows dependencies to abstract things away, but still.)

We don't prevent people from doing the following:

```js
(async () => {
  await delay(100);
  self.onfetch = e => ...;
})();
```

and we should similarly not prevent them from doing the following:

```js
await delay(100);
self.onfetch = e => ...;
```

**Comment by littledan** [comment]
Should we have this conversation here or in https://github.com/w3c/ServiceWorker/issues/1407 ? We might be able to engage more ServiceWorker experts in their repository.

**Comment by domenic** [comment]
Thanks, I'd missed or forgotten about that. I will move my comment there and mark it off-topic for here, as indeed the better discussion seems to be over there.
